name: Deploy Pipeline

on:
  push:
    branches: [ main ]

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_env: "dev"
      TF_VAR_domain_name: "aws-workshops.com"

      # Set these as GitHub repo secrets:
      # TF_STATE_BUCKET  (e.g., healthtech-tfstate-637423443220)
      # TF_LOCK_TABLE    (e.g., healthtech-terraform-locks)
      TF_STATE_KEY: "healthtech/dev/terraform.tfstate"

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: *****arn:aws:iam::637423443220:role/****GitHubActionRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (remote state)
        run: |
          terraform init -upgrade -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
            -backend-config="encrypt=true"
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
